services:
  price-adv:
    build: ./
    container_name: price-adv
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge